#!/bin/bash
echo "========================================"
echo "ZainOne Orchestrator Studio"
echo "========================================"
echo ""
echo "Starting Backend Server..."
gnome-terminal -- bash -c "cd backend && python3 -m uvicorn app.main:app --reload --host 0.0.0.0 --port 8000; exec bash"
echo ""
echo "Waiting 3 seconds for backend to initialize..."
sleep 3
echo ""
echo "Starting Frontend Development Server..."
gnome-terminal -- bash -c "cd frontend && npm start; exec bash"
echo ""
echo "========================================"
echo "Both servers are starting!"
echo "Backend: http://localhost:8000"
echo "Frontend: http://localhost:3000"
echo "API Docs: http://localhost:8000/docs"
echo "========================================"
